@Re_Backend.Api_HostAddress = http://localhost:5151
@Re_Backend.Authorization = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIyMDEyIiwicm9sZSI6IlVzZXIiLCJuYmYiOjE3NTk5MzIwMzYsImV4cCI6MTc2MDUzNjgzNiwiaWF0IjoxNzU5OTMyMDM2LCJpc3MiOiJBZDY0IiwiYXVkIjoiQWQ2NCJ9.FjmkEQ9fwB3_XYMd3SJWOd8OZDW4z8SS2ZfvsZQ1q1o
GET {{Re_Backend.Api_HostAddress}}/weatherforecast/
Accept: application/json
###

GET {{Re_Backend.Api_HostAddress}}/api/pages
Accept: application/json
Authorization:Bearer {{Re_Backend.Authorization}}
###
