@Re_Backend.Api_HostAddress = http://localhost:5151
@Re_Backend.Authorization = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiJUZXN0VXNlciIsIm5iZiI6MTc0MzkyNTk2NywiZXhwIjoxNzQzOTI5NTY3LCJpYXQiOjE3NDM5MjU5NjcsImlzcyI6IkFkNjQiLCJhdWQiOiJBZDY0In0.RSEoRFor0RX2ihxPcMS8Tuw27jkRm5DPmTUpgD_MvME
GET {{Re_Backend.Api_HostAddress}}/weatherforecast/
Accept: application/json
###

GET {{Re_Backend.Api_HostAddress}}/api/values
Accept: application/json
Authorization:Bearer {{Re_Backend.Authorization}}
###
